<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2eUir5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2eUir5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2eUir5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2eUir5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2eUir5\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2eUir5',
    'container.build_id' => '2a889dc5',
    'container.build_time' => 1732574808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2eUir5');
