<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEMcPUii\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEMcPUii/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEMcPUii.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEMcPUii\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEMcPUii\App_KernelDevDebugContainer([
    'container.build_hash' => 'EMcPUii',
    'container.build_id' => '3624f4a6',
    'container.build_time' => 1733302248,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEMcPUii');
