<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJFjJR1H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJFjJR1H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJFjJR1H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJFjJR1H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJFjJR1H\App_KernelDevDebugContainer([
    'container.build_hash' => 'JFjJR1H',
    'container.build_id' => 'b6f9538b',
    'container.build_time' => 1732047105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJFjJR1H');
