<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_react-dom_client_js-node_modules_react_jsx-runtime_js.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'styles' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/styles.css',
            ],
        ],
    ],
],

]];
